package com.luxpretty.app.auth;

import com.luxpretty.app.users.domain.AuthProvider;
import com.luxpretty.app.users.domain.Role;
import com.luxpretty.app.users.domain.User;
import com.luxpretty.app.users.repo.UserRepository;
import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;
import jakarta.servlet.http.Cookie;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.mock.web.MockHttpServletRequest;
import org.springframework.mock.web.MockHttpServletResponse;
import org.springframework.security.core.Authentication;
import org.springframework.security.oauth2.core.OAuth2AuthenticationException;
import org.springframework.test.util.ReflectionTestUtils;

import javax.crypto.SecretKey;
import java.nio.charset.StandardCharsets;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class OAuth2AuthenticationSuccessHandlerTests {

    @Mock
    private UserRepository userRepository;

    @Mock
    private com.luxpretty.app.users.app.UserRoleService userRoleService;

    private TokenService tokenService;
    private OAuth2AuthenticationSuccessHandler handler;

    private static final String TEST_SECRET = "test-secret-key-for-unit-tests-min-32-bytes-ok";
    private static final String REDIRECT_URI = "http://localhost:4300/oauth2/redirect";

    @BeforeEach
    void setUp() {
        tokenService = new TokenService();
        ReflectionTestUtils.setField(tokenService, "tokenSecret", TEST_SECRET);
        ReflectionTestUtils.setField(tokenService, "tokenExpirationMs", 86400000L);

        handler = new OAuth2AuthenticationSuccessHandler(tokenService, userRepository, userRoleService);
        ReflectionTestUtils.setField(handler, "authorizedRedirectUri", REDIRECT_URI);
    }

    // B2.4: Token generated by success handler contains email and role claims
    @Test
    void onAuthenticationSuccess_generatesTokenWithEmailAndRole() throws Exception {
        User user = User.builder()
            .id(1L)
            .name("Sophie Martin")
            .email("sophie@salon.fr")
            .provider(AuthProvider.GOOGLE)
            .emailVerified(true)
            .build();

        when(userRepository.findById(1L)).thenReturn(Optional.of(user));
        when(userRoleService.findUserTenantIds(1L)).thenReturn(java.util.List.of(42L));
        when(userRoleService.resolveRoles(1L, 42L))
                .thenReturn(java.util.Set.of(com.luxpretty.app.users.domain.Role.PRO));

        CustomOAuth2User oAuth2User = mock(CustomOAuth2User.class);
        when(oAuth2User.getUserId()).thenReturn(1L);

        Authentication authentication = mock(Authentication.class);
        when(authentication.getPrincipal()).thenReturn(oAuth2User);

        MockHttpServletRequest request = new MockHttpServletRequest();
        MockHttpServletResponse response = new MockHttpServletResponse();

        handler.onAuthenticationSuccess(request, response, authentication);

        // Parse redirect URL and extract token
        String location = response.getRedirectedUrl();
        assertThat(location).isNotNull().startsWith(REDIRECT_URI + "?token=");

        String token = location.substring(location.indexOf("token=") + 6);

        // Decode and verify JWT claims
        SecretKey key = Keys.hmacShaKeyFor(TEST_SECRET.getBytes(StandardCharsets.UTF_8));
        Claims claims = Jwts.parser()
            .verifyWith(key)
            .build()
            .parseSignedClaims(token)
            .getPayload();

        assertThat(claims.getSubject()).isEqualTo("1");
        assertThat(claims.get("email", String.class)).isEqualTo("sophie@salon.fr");
        assertThat(claims.get("roles", java.util.List.class)).containsExactly("PRO");
        assertThat(claims.get("activeTenantId", Long.class)).isEqualTo(42L);
    }

    // Lot6: user not found after OAuth2 flow → throws OAuth2AuthenticationException
    @Test
    void onAuthenticationSuccess_userNotFound_throwsOAuth2Exception() {
        when(userRepository.findById(42L)).thenReturn(Optional.empty());

        CustomOAuth2User oAuth2User = mock(CustomOAuth2User.class);
        when(oAuth2User.getUserId()).thenReturn(42L);

        Authentication authentication = mock(Authentication.class);
        when(authentication.getPrincipal()).thenReturn(oAuth2User);

        MockHttpServletRequest request = new MockHttpServletRequest();
        MockHttpServletResponse response = new MockHttpServletResponse();

        assertThatThrownBy(() -> handler.onAuthenticationSuccess(request, response, authentication))
            .isInstanceOf(OAuth2AuthenticationException.class);
    }

    // Lot6: success handler clears role-hint cookie (prevents stale role on next OAuth login)
    @Test
    void onAuthenticationSuccess_clearsRoleHintCookie() throws Exception {
        User user = User.builder()
            .id(1L).name("Sophie").email("sophie@salon.fr")
            .provider(AuthProvider.GOOGLE).emailVerified(true).build();

        when(userRepository.findById(1L)).thenReturn(Optional.of(user));

        CustomOAuth2User oAuth2User = mock(CustomOAuth2User.class);
        when(oAuth2User.getUserId()).thenReturn(1L);

        Authentication authentication = mock(Authentication.class);
        when(authentication.getPrincipal()).thenReturn(oAuth2User);

        MockHttpServletRequest request = new MockHttpServletRequest();
        MockHttpServletResponse response = new MockHttpServletResponse();

        handler.onAuthenticationSuccess(request, response, authentication);

        Cookie roleHint = response.getCookie(OAuth2RoleHintFilter.ROLE_HINT_COOKIE);
        assertThat(roleHint).isNotNull();
        assertThat(roleHint.getMaxAge()).isEqualTo(0);
        assertThat(roleHint.getPath()).isEqualTo("/");
    }
}
