-- Tenant schema baseline (Oracle).
--
-- This migration creates the full set of tenant-scoped tables for a brand-new
-- salon schema. Each placeholder is resolved by TenantFlywayService when it
-- invokes Flyway against a specific tenant schema:
--   ${tenantSchema}  → e.g. TENANT_SALON_PARIS
--   ${appSchema}     → the shared application schema (e.g. APPUSER)
--
-- For LEGACY tenants (provisioned before this migration existed), Flyway
-- baselines them at V1 via baselineOnMigrate=true; the CREATE TABLE statements
-- below are NOT executed against an existing schema. New ALTER migrations land
-- in V2+ on top of that baseline.
--
-- Mirrored from TenantSchemaManager.createTenantTables(); keep both in sync
-- until the H2 test path is decommissioned.

-- ── Cross-schema synonyms (must be fully qualified, run before USE TENANT) ──
CREATE OR REPLACE SYNONYM "${tenantSchema}"."USERS"
    FOR "${appSchema}"."USERS";

CREATE OR REPLACE SYNONYM "${tenantSchema}"."TENANTS"
    FOR "${appSchema}"."TENANTS";

-- ── Tenant tables ──
CREATE TABLE "${tenantSchema}".CATEGORIES (
    ID           NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME         VARCHAR2(255 CHAR) NOT NULL,
    DESCRIPTION  VARCHAR2(255 CHAR),
    CONSTRAINT UK_CATEGORY_NAME UNIQUE (NAME)
);

CREATE TABLE "${tenantSchema}".SERVICES (
    ID            NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME          VARCHAR2(255 CHAR) NOT NULL,
    PRICE         NUMBER(10) NOT NULL,
    DESCRIPTION   VARCHAR2(255 CHAR) NOT NULL,
    STATUS        VARCHAR2(255 CHAR) NOT NULL,
    DURATION      NUMBER(10) NOT NULL,
    DISPLAY_ORDER NUMBER(10),
    CATEGORY_ID   NUMBER(19) NOT NULL,
    CONSTRAINT FK_CARE_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES "${tenantSchema}".CATEGORIES(ID)
);

CREATE TABLE "${tenantSchema}".CARE_IMAGES (
    ID          NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME        VARCHAR2(255 CHAR) NOT NULL,
    IMAGE_ORDER NUMBER(10) NOT NULL,
    FILENAME    VARCHAR2(100 CHAR) NOT NULL,
    FILE_PATH   VARCHAR2(500 CHAR) NOT NULL,
    CARE_ID     NUMBER(19) NOT NULL,
    CONSTRAINT FK_CARE_IMAGE_CARE FOREIGN KEY (CARE_ID) REFERENCES "${tenantSchema}".SERVICES(ID)
);

CREATE TABLE "${tenantSchema}".OPENING_HOURS (
    ID          NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DAY_OF_WEEK NUMBER(10) NOT NULL,
    OPEN_TIME   TIMESTAMP NOT NULL,
    CLOSE_TIME  TIMESTAMP NOT NULL,
    EMPLOYEE_ID NUMBER(19)
);

CREATE TABLE "${tenantSchema}".BLOCKED_SLOTS (
    ID          NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SLOT_DATE   DATE NOT NULL,
    START_TIME  TIMESTAMP,
    END_TIME    TIMESTAMP,
    FULL_DAY    NUMBER(1) NOT NULL,
    REASON      VARCHAR2(500 CHAR),
    EMPLOYEE_ID NUMBER(19)
);

-- USER_ID references the shared USERS table (via synonym above) — no FK constraint.
CREATE TABLE "${tenantSchema}".CARE_BOOKINGS (
    ID               NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID          NUMBER(19) NOT NULL,
    CARE_ID          NUMBER(19) NOT NULL,
    QUANTITY         NUMBER(10) NOT NULL,
    APPOINTMENT_DATE DATE NOT NULL,
    APPOINTMENT_TIME TIMESTAMP NOT NULL,
    STATUS           VARCHAR2(255 CHAR) NOT NULL,
    CREATED_AT       TIMESTAMP NOT NULL,
    EMPLOYEE_ID      NUMBER(19),
    SALON_CLIENT_ID  NUMBER(19),
    CONSTRAINT FK_BOOKING_CARE FOREIGN KEY (CARE_ID) REFERENCES "${tenantSchema}".SERVICES(ID),
    CONSTRAINT UK_BOOKING_SLOT UNIQUE (APPOINTMENT_DATE, APPOINTMENT_TIME, CARE_ID)
);

CREATE TABLE "${tenantSchema}".EMPLOYEES (
    ID         NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID    NUMBER(19) NOT NULL,
    NAME       VARCHAR2(255 CHAR) NOT NULL,
    EMAIL      VARCHAR2(255 CHAR) NOT NULL,
    PHONE      VARCHAR2(255 CHAR),
    ACTIVE     NUMBER(1) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT UK_EMPLOYEE_USER UNIQUE (USER_ID)
);

CREATE TABLE "${tenantSchema}".EMPLOYEE_CARES (
    EMPLOYEE_ID NUMBER(19) NOT NULL,
    CARE_ID     NUMBER(19) NOT NULL,
    CONSTRAINT FK_EC_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES "${tenantSchema}".EMPLOYEES(ID),
    CONSTRAINT FK_EC_CARE FOREIGN KEY (CARE_ID) REFERENCES "${tenantSchema}".SERVICES(ID),
    CONSTRAINT PK_EMPLOYEE_CARES PRIMARY KEY (EMPLOYEE_ID, CARE_ID)
);

CREATE TABLE "${tenantSchema}".LEAVE_REQUESTS (
    ID            NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EMPLOYEE_ID   NUMBER(19) NOT NULL,
    LEAVE_TYPE    VARCHAR2(255 CHAR) NOT NULL,
    STATUS        VARCHAR2(255 CHAR) NOT NULL,
    START_DATE    DATE NOT NULL,
    END_DATE      DATE NOT NULL,
    REASON        VARCHAR2(500 CHAR),
    DOCUMENT_PATH VARCHAR2(500 CHAR),
    REVIEWER_NOTE VARCHAR2(500 CHAR),
    CREATED_AT    TIMESTAMP NOT NULL,
    REVIEWED_AT   TIMESTAMP,
    VERSION       NUMBER(19),
    CONSTRAINT FK_LEAVE_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES "${tenantSchema}".EMPLOYEES(ID)
);

CREATE TABLE "${tenantSchema}".EMPLOYEE_DOCUMENTS (
    ID                  NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EMPLOYEE_ID         NUMBER(19) NOT NULL,
    DOC_TYPE            VARCHAR2(255 CHAR) NOT NULL,
    TITLE               VARCHAR2(255 CHAR) NOT NULL,
    FILENAME            VARCHAR2(255 CHAR) NOT NULL,
    FILE_PATH           VARCHAR2(500 CHAR) NOT NULL,
    UPLOADED_BY_USER_ID NUMBER(19) NOT NULL,
    CREATED_AT          TIMESTAMP NOT NULL,
    CONSTRAINT FK_DOC_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES "${tenantSchema}".EMPLOYEES(ID)
);

CREATE TABLE "${tenantSchema}".POSTS (
    ID                NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    POST_TYPE         VARCHAR2(255 CHAR) NOT NULL,
    CAPTION           VARCHAR2(1000 CHAR),
    BEFORE_IMAGE_PATH VARCHAR2(500 CHAR),
    AFTER_IMAGE_PATH  VARCHAR2(500 CHAR),
    CARE_ID           NUMBER(19),
    CARE_NAME         VARCHAR2(255 CHAR),
    CREATED_AT        TIMESTAMP NOT NULL
);

CREATE TABLE "${tenantSchema}".POST_IMAGES (
    ID          NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    POST_ID     NUMBER(19) NOT NULL,
    IMAGE_PATH  VARCHAR2(500 CHAR) NOT NULL,
    IMAGE_ORDER NUMBER(10) NOT NULL,
    CONSTRAINT FK_POST_IMAGE_POST FOREIGN KEY (POST_ID) REFERENCES "${tenantSchema}".POSTS(ID)
);

CREATE TABLE "${tenantSchema}".HOLIDAY_EXCEPTIONS (
    ID           NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    HOLIDAY_DATE DATE NOT NULL,
    OPEN         NUMBER(1) NOT NULL
);

CREATE TABLE "${tenantSchema}".CLIENT_PROFILES (
    ID                   NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID              NUMBER(19) NOT NULL,
    NOTES                VARCHAR2(2000 CHAR),
    SKIN_TYPE            VARCHAR2(100 CHAR),
    HAIR_TYPE            VARCHAR2(100 CHAR),
    ALLERGIES            VARCHAR2(500 CHAR),
    PREFERENCES          VARCHAR2(500 CHAR),
    CONSENT_PHOTOS       NUMBER(1) NOT NULL,
    CONSENT_PUBLIC_SHARE NUMBER(1) NOT NULL,
    CONSENT_GIVEN_AT     TIMESTAMP,
    CREATED_AT           TIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP,
    UPDATED_BY           NUMBER(19),
    CONSTRAINT UK_CLIENT_PROFILE_USER UNIQUE (USER_ID)
);

CREATE TABLE "${tenantSchema}".VISIT_RECORDS (
    ID                   NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLIENT_PROFILE_ID    NUMBER(19) NOT NULL,
    BOOKING_ID           NUMBER(19),
    CARE_ID              NUMBER(19),
    CARE_NAME            VARCHAR2(255 CHAR),
    VISIT_DATE           DATE NOT NULL,
    PRACTITIONER_NOTES   VARCHAR2(2000 CHAR),
    PRODUCTS_USED        VARCHAR2(1000 CHAR),
    SATISFACTION_SCORE   NUMBER(10),
    SATISFACTION_COMMENT VARCHAR2(500 CHAR),
    CREATED_AT           TIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP,
    UPDATED_BY           NUMBER(19),
    CONSTRAINT FK_VISIT_PROFILE FOREIGN KEY (CLIENT_PROFILE_ID) REFERENCES "${tenantSchema}".CLIENT_PROFILES(ID)
);

CREATE TABLE "${tenantSchema}".VISIT_PHOTOS (
    ID              NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    VISIT_RECORD_ID NUMBER(19) NOT NULL,
    PHOTO_TYPE      VARCHAR2(20 CHAR) NOT NULL,
    IMAGE_PATH      VARCHAR2(500 CHAR) NOT NULL,
    IMAGE_ORDER     NUMBER(10) NOT NULL,
    CREATED_AT      TIMESTAMP NOT NULL,
    UPLOADED_BY     NUMBER(19),
    CONSTRAINT FK_PHOTO_VISIT FOREIGN KEY (VISIT_RECORD_ID) REFERENCES "${tenantSchema}".VISIT_RECORDS(ID)
);

CREATE TABLE "${tenantSchema}".CLIENT_REMINDERS (
    ID               NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID          NUMBER(19) NOT NULL,
    CARE_ID          NUMBER(19),
    CARE_NAME        VARCHAR2(255 CHAR),
    RECOMMENDED_DATE DATE,
    MESSAGE          VARCHAR2(500 CHAR),
    SENT             NUMBER(1) NOT NULL,
    CREATED_AT       TIMESTAMP NOT NULL,
    CREATED_BY       NUMBER(19)
);

CREATE TABLE "${tenantSchema}".EMPLOYEE_PERMISSIONS (
    ID           NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EMPLOYEE_ID  NUMBER(19) NOT NULL,
    DOMAIN       VARCHAR2(30 CHAR) NOT NULL,
    ACCESS_LEVEL VARCHAR2(10 CHAR) NOT NULL,
    CONSTRAINT FK_EMP_PERM_EMP FOREIGN KEY (EMPLOYEE_ID) REFERENCES "${tenantSchema}".EMPLOYEES(ID),
    CONSTRAINT UQ_EMP_PERM UNIQUE (EMPLOYEE_ID, DOMAIN)
);

CREATE TABLE "${tenantSchema}".SALON_CLIENTS (
    ID            NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME          VARCHAR2(255 CHAR) NOT NULL,
    PHONE         VARCHAR2(20 CHAR),
    EMAIL         VARCHAR2(255 CHAR),
    DATE_OF_BIRTH DATE,
    NOTES         VARCHAR2(500 CHAR),
    USER_ID       NUMBER(19),
    IS_MANUAL     NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT    TIMESTAMP NOT NULL,
    CREATED_BY    NUMBER(19)
);

-- ── GRANTs to the application user (so the app DataSource can DML these tables) ──
GRANT SELECT, INSERT, UPDATE, DELETE ON "${tenantSchema}".CATEGORIES           TO "${appSchema}";
GRANT SELECT, INSERT, UPDATE, DELETE ON "${tenantSchema}".SERVICES             TO "${appSchema}";
GRANT SELECT, INSERT, UPDATE, DELETE ON "${tenantSchema}".CARE_IMAGES          TO "${appSchema}";
GRANT SELECT, INSERT, UPDATE, DELETE ON "${tenantSchema}".OPENING_HOURS        TO "${appSchema}";
GRANT SELECT, INSERT, UPDATE, DELETE ON "${tenantSchema}".BLOCKED_SLOTS        TO "${appSchema}";
GRANT SELECT, INSERT, UPDATE, DELETE ON "${tenantSchema}".CARE_BOOKINGS        TO "${appSchema}";
GRANT SELECT, INSERT, UPDATE, DELETE ON "${tenantSchema}".EMPLOYEES            TO "${appSchema}";
GRANT SELECT, INSERT, UPDATE, DELETE ON "${tenantSchema}".EMPLOYEE_CARES       TO "${appSchema}";
GRANT SELECT, INSERT, UPDATE, DELETE ON "${tenantSchema}".LEAVE_REQUESTS       TO "${appSchema}";
GRANT SELECT, INSERT, UPDATE, DELETE ON "${tenantSchema}".EMPLOYEE_DOCUMENTS   TO "${appSchema}";
GRANT SELECT, INSERT, UPDATE, DELETE ON "${tenantSchema}".POSTS                TO "${appSchema}";
GRANT SELECT, INSERT, UPDATE, DELETE ON "${tenantSchema}".POST_IMAGES          TO "${appSchema}";
GRANT SELECT, INSERT, UPDATE, DELETE ON "${tenantSchema}".HOLIDAY_EXCEPTIONS   TO "${appSchema}";
GRANT SELECT, INSERT, UPDATE, DELETE ON "${tenantSchema}".SALON_CLIENTS        TO "${appSchema}";
GRANT SELECT, INSERT, UPDATE, DELETE ON "${tenantSchema}".CLIENT_PROFILES      TO "${appSchema}";
GRANT SELECT, INSERT, UPDATE, DELETE ON "${tenantSchema}".VISIT_RECORDS        TO "${appSchema}";
GRANT SELECT, INSERT, UPDATE, DELETE ON "${tenantSchema}".VISIT_PHOTOS         TO "${appSchema}";
GRANT SELECT, INSERT, UPDATE, DELETE ON "${tenantSchema}".CLIENT_REMINDERS     TO "${appSchema}";
GRANT SELECT, INSERT, UPDATE, DELETE ON "${tenantSchema}".EMPLOYEE_PERMISSIONS TO "${appSchema}";
