-- V8: per-tenant feature flags (default seeded by tier, admin-overridable)
CREATE TABLE TENANT_FEATURES (
  FEATURE_KEY VARCHAR2(64) PRIMARY KEY,
  ENABLED     NUMBER(1) NOT NULL CHECK (ENABLED IN (0,1)),
  SOURCE      VARCHAR2(16) NOT NULL CHECK (SOURCE IN ('TIER_DEFAULT','ADMIN_OVERRIDE')),
  UPDATED_AT  TIMESTAMP WITH TIME ZONE NOT NULL
);
