export interface Country {
  code: string;
  name: string;
  nameEn: string;
  flag: string;
}

export const POPULAR_COUNTRY_CODES: string[] = [
  'FR', 'BE', 'CH', 'LU', 'DE', 'ES', 'IT', 'GB', 'MA', 'CA',
];

export const COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afghanistan', nameEn: 'Afghanistan', flag: '\u{1F1E6}\u{1F1EB}' },
  { code: 'ZA', name: 'Afrique du Sud', nameEn: 'South Africa', flag: '\u{1F1FF}\u{1F1E6}' },
  { code: 'AL', name: 'Albanie', nameEn: 'Albania', flag: '\u{1F1E6}\u{1F1F1}' },
  { code: 'DZ', name: 'Alg\u00e9rie', nameEn: 'Algeria', flag: '\u{1F1E9}\u{1F1FF}' },
  { code: 'DE', name: 'Allemagne', nameEn: 'Germany', flag: '\u{1F1E9}\u{1F1EA}' },
  { code: 'AD', name: 'Andorre', nameEn: 'Andorra', flag: '\u{1F1E6}\u{1F1E9}' },
  { code: 'AO', name: 'Angola', nameEn: 'Angola', flag: '\u{1F1E6}\u{1F1F4}' },
  { code: 'AG', name: 'Antigua-et-Barbuda', nameEn: 'Antigua and Barbuda', flag: '\u{1F1E6}\u{1F1EC}' },
  { code: 'SA', name: 'Arabie saoudite', nameEn: 'Saudi Arabia', flag: '\u{1F1F8}\u{1F1E6}' },
  { code: 'AR', name: 'Argentine', nameEn: 'Argentina', flag: '\u{1F1E6}\u{1F1F7}' },
  { code: 'AM', name: 'Arm\u00e9nie', nameEn: 'Armenia', flag: '\u{1F1E6}\u{1F1F2}' },
  { code: 'AU', name: 'Australie', nameEn: 'Australia', flag: '\u{1F1E6}\u{1F1FA}' },
  { code: 'AT', name: 'Autriche', nameEn: 'Austria', flag: '\u{1F1E6}\u{1F1F9}' },
  { code: 'AZ', name: 'Azerba\u00efdjan', nameEn: 'Azerbaijan', flag: '\u{1F1E6}\u{1F1FF}' },
  { code: 'BS', name: 'Bahamas', nameEn: 'Bahamas', flag: '\u{1F1E7}\u{1F1F8}' },
  { code: 'BH', name: 'Bahre\u00efn', nameEn: 'Bahrain', flag: '\u{1F1E7}\u{1F1ED}' },
  { code: 'BD', name: 'Bangladesh', nameEn: 'Bangladesh', flag: '\u{1F1E7}\u{1F1E9}' },
  { code: 'BB', name: 'Barbade', nameEn: 'Barbados', flag: '\u{1F1E7}\u{1F1E7}' },
  { code: 'BE', name: 'Belgique', nameEn: 'Belgium', flag: '\u{1F1E7}\u{1F1EA}' },
  { code: 'BZ', name: 'Belize', nameEn: 'Belize', flag: '\u{1F1E7}\u{1F1FF}' },
  { code: 'BJ', name: 'B\u00e9nin', nameEn: 'Benin', flag: '\u{1F1E7}\u{1F1EF}' },
  { code: 'BT', name: 'Bhoutan', nameEn: 'Bhutan', flag: '\u{1F1E7}\u{1F1F9}' },
  { code: 'BY', name: 'Bi\u00e9lorussie', nameEn: 'Belarus', flag: '\u{1F1E7}\u{1F1FE}' },
  { code: 'BO', name: 'Bolivie', nameEn: 'Bolivia', flag: '\u{1F1E7}\u{1F1F4}' },
  { code: 'BA', name: 'Bosnie-Herz\u00e9govine', nameEn: 'Bosnia and Herzegovina', flag: '\u{1F1E7}\u{1F1E6}' },
  { code: 'BW', name: 'Botswana', nameEn: 'Botswana', flag: '\u{1F1E7}\u{1F1FC}' },
  { code: 'BR', name: 'Br\u00e9sil', nameEn: 'Brazil', flag: '\u{1F1E7}\u{1F1F7}' },
  { code: 'BN', name: 'Brunei', nameEn: 'Brunei', flag: '\u{1F1E7}\u{1F1F3}' },
  { code: 'BG', name: 'Bulgarie', nameEn: 'Bulgaria', flag: '\u{1F1E7}\u{1F1EC}' },
  { code: 'BF', name: 'Burkina Faso', nameEn: 'Burkina Faso', flag: '\u{1F1E7}\u{1F1EB}' },
  { code: 'BI', name: 'Burundi', nameEn: 'Burundi', flag: '\u{1F1E7}\u{1F1EE}' },
  { code: 'KH', name: 'Cambodge', nameEn: 'Cambodia', flag: '\u{1F1F0}\u{1F1ED}' },
  { code: 'CM', name: 'Cameroun', nameEn: 'Cameroon', flag: '\u{1F1E8}\u{1F1F2}' },
  { code: 'CA', name: 'Canada', nameEn: 'Canada', flag: '\u{1F1E8}\u{1F1E6}' },
  { code: 'CV', name: 'Cap-Vert', nameEn: 'Cape Verde', flag: '\u{1F1E8}\u{1F1FB}' },
  { code: 'CF', name: 'R\u00e9publique centrafricaine', nameEn: 'Central African Republic', flag: '\u{1F1E8}\u{1F1EB}' },
  { code: 'CL', name: 'Chili', nameEn: 'Chile', flag: '\u{1F1E8}\u{1F1F1}' },
  { code: 'CN', name: 'Chine', nameEn: 'China', flag: '\u{1F1E8}\u{1F1F3}' },
  { code: 'CY', name: 'Chypre', nameEn: 'Cyprus', flag: '\u{1F1E8}\u{1F1FE}' },
  { code: 'CO', name: 'Colombie', nameEn: 'Colombia', flag: '\u{1F1E8}\u{1F1F4}' },
  { code: 'KM', name: 'Comores', nameEn: 'Comoros', flag: '\u{1F1F0}\u{1F1F2}' },
  { code: 'CG', name: 'Congo', nameEn: 'Congo', flag: '\u{1F1E8}\u{1F1EC}' },
  { code: 'CD', name: 'R\u00e9publique d\u00e9mocratique du Congo', nameEn: 'Democratic Republic of the Congo', flag: '\u{1F1E8}\u{1F1E9}' },
  { code: 'KR', name: 'Cor\u00e9e du Sud', nameEn: 'South Korea', flag: '\u{1F1F0}\u{1F1F7}' },
  { code: 'KP', name: 'Cor\u00e9e du Nord', nameEn: 'North Korea', flag: '\u{1F1F0}\u{1F1F5}' },
  { code: 'CR', name: 'Costa Rica', nameEn: 'Costa Rica', flag: '\u{1F1E8}\u{1F1F7}' },
  { code: 'CI', name: "C\u00f4te d'Ivoire", nameEn: 'Ivory Coast', flag: '\u{1F1E8}\u{1F1EE}' },
  { code: 'HR', name: 'Croatie', nameEn: 'Croatia', flag: '\u{1F1ED}\u{1F1F7}' },
  { code: 'CU', name: 'Cuba', nameEn: 'Cuba', flag: '\u{1F1E8}\u{1F1FA}' },
  { code: 'DK', name: 'Danemark', nameEn: 'Denmark', flag: '\u{1F1E9}\u{1F1F0}' },
  { code: 'DJ', name: 'Djibouti', nameEn: 'Djibouti', flag: '\u{1F1E9}\u{1F1EF}' },
  { code: 'DM', name: 'Dominique', nameEn: 'Dominica', flag: '\u{1F1E9}\u{1F1F2}' },
  { code: 'EG', name: '\u00c9gypte', nameEn: 'Egypt', flag: '\u{1F1EA}\u{1F1EC}' },
  { code: 'AE', name: '\u00c9mirats arabes unis', nameEn: 'United Arab Emirates', flag: '\u{1F1E6}\u{1F1EA}' },
  { code: 'EC', name: '\u00c9quateur', nameEn: 'Ecuador', flag: '\u{1F1EA}\u{1F1E8}' },
  { code: 'ER', name: '\u00c9rythr\u00e9e', nameEn: 'Eritrea', flag: '\u{1F1EA}\u{1F1F7}' },
  { code: 'ES', name: 'Espagne', nameEn: 'Spain', flag: '\u{1F1EA}\u{1F1F8}' },
  { code: 'EE', name: 'Estonie', nameEn: 'Estonia', flag: '\u{1F1EA}\u{1F1EA}' },
  { code: 'SZ', name: 'Eswatini', nameEn: 'Eswatini', flag: '\u{1F1F8}\u{1F1FF}' },
  { code: 'US', name: '\u00c9tats-Unis', nameEn: 'United States', flag: '\u{1F1FA}\u{1F1F8}' },
  { code: 'ET', name: '\u00c9thiopie', nameEn: 'Ethiopia', flag: '\u{1F1EA}\u{1F1F9}' },
  { code: 'FJ', name: 'Fidji', nameEn: 'Fiji', flag: '\u{1F1EB}\u{1F1EF}' },
  { code: 'FI', name: 'Finlande', nameEn: 'Finland', flag: '\u{1F1EB}\u{1F1EE}' },
  { code: 'FR', name: 'France', nameEn: 'France', flag: '\u{1F1EB}\u{1F1F7}' },
  { code: 'GA', name: 'Gabon', nameEn: 'Gabon', flag: '\u{1F1EC}\u{1F1E6}' },
  { code: 'GM', name: 'Gambie', nameEn: 'Gambia', flag: '\u{1F1EC}\u{1F1F2}' },
  { code: 'GE', name: 'G\u00e9orgie', nameEn: 'Georgia', flag: '\u{1F1EC}\u{1F1EA}' },
  { code: 'GH', name: 'Ghana', nameEn: 'Ghana', flag: '\u{1F1EC}\u{1F1ED}' },
  { code: 'GR', name: 'Gr\u00e8ce', nameEn: 'Greece', flag: '\u{1F1EC}\u{1F1F7}' },
  { code: 'GD', name: 'Grenade', nameEn: 'Grenada', flag: '\u{1F1EC}\u{1F1E9}' },
  { code: 'GT', name: 'Guatemala', nameEn: 'Guatemala', flag: '\u{1F1EC}\u{1F1F9}' },
  { code: 'GN', name: 'Guin\u00e9e', nameEn: 'Guinea', flag: '\u{1F1EC}\u{1F1F3}' },
  { code: 'GW', name: 'Guin\u00e9e-Bissau', nameEn: 'Guinea-Bissau', flag: '\u{1F1EC}\u{1F1FC}' },
  { code: 'GQ', name: 'Guin\u00e9e \u00e9quatoriale', nameEn: 'Equatorial Guinea', flag: '\u{1F1EC}\u{1F1F6}' },
  { code: 'GY', name: 'Guyana', nameEn: 'Guyana', flag: '\u{1F1EC}\u{1F1FE}' },
  { code: 'HT', name: 'Ha\u00efti', nameEn: 'Haiti', flag: '\u{1F1ED}\u{1F1F9}' },
  { code: 'HN', name: 'Honduras', nameEn: 'Honduras', flag: '\u{1F1ED}\u{1F1F3}' },
  { code: 'HU', name: 'Hongrie', nameEn: 'Hungary', flag: '\u{1F1ED}\u{1F1FA}' },
  { code: 'IN', name: 'Inde', nameEn: 'India', flag: '\u{1F1EE}\u{1F1F3}' },
  { code: 'ID', name: 'Indon\u00e9sie', nameEn: 'Indonesia', flag: '\u{1F1EE}\u{1F1E9}' },
  { code: 'IQ', name: 'Irak', nameEn: 'Iraq', flag: '\u{1F1EE}\u{1F1F6}' },
  { code: 'IR', name: 'Iran', nameEn: 'Iran', flag: '\u{1F1EE}\u{1F1F7}' },
  { code: 'IE', name: 'Irlande', nameEn: 'Ireland', flag: '\u{1F1EE}\u{1F1EA}' },
  { code: 'IS', name: 'Islande', nameEn: 'Iceland', flag: '\u{1F1EE}\u{1F1F8}' },
  { code: 'IL', name: 'Isra\u00ebl', nameEn: 'Israel', flag: '\u{1F1EE}\u{1F1F1}' },
  { code: 'IT', name: 'Italie', nameEn: 'Italy', flag: '\u{1F1EE}\u{1F1F9}' },
  { code: 'JM', name: 'Jama\u00efque', nameEn: 'Jamaica', flag: '\u{1F1EF}\u{1F1F2}' },
  { code: 'JP', name: 'Japon', nameEn: 'Japan', flag: '\u{1F1EF}\u{1F1F5}' },
  { code: 'JO', name: 'Jordanie', nameEn: 'Jordan', flag: '\u{1F1EF}\u{1F1F4}' },
  { code: 'KZ', name: 'Kazakhstan', nameEn: 'Kazakhstan', flag: '\u{1F1F0}\u{1F1FF}' },
  { code: 'KE', name: 'Kenya', nameEn: 'Kenya', flag: '\u{1F1F0}\u{1F1EA}' },
  { code: 'KG', name: 'Kirghizistan', nameEn: 'Kyrgyzstan', flag: '\u{1F1F0}\u{1F1EC}' },
  { code: 'KI', name: 'Kiribati', nameEn: 'Kiribati', flag: '\u{1F1F0}\u{1F1EE}' },
  { code: 'KW', name: 'Kowe\u00eft', nameEn: 'Kuwait', flag: '\u{1F1F0}\u{1F1FC}' },
  { code: 'LA', name: 'Laos', nameEn: 'Laos', flag: '\u{1F1F1}\u{1F1E6}' },
  { code: 'LS', name: 'Lesotho', nameEn: 'Lesotho', flag: '\u{1F1F1}\u{1F1F8}' },
  { code: 'LV', name: 'Lettonie', nameEn: 'Latvia', flag: '\u{1F1F1}\u{1F1FB}' },
  { code: 'LB', name: 'Liban', nameEn: 'Lebanon', flag: '\u{1F1F1}\u{1F1E7}' },
  { code: 'LR', name: 'Lib\u00e9ria', nameEn: 'Liberia', flag: '\u{1F1F1}\u{1F1F7}' },
  { code: 'LY', name: 'Libye', nameEn: 'Libya', flag: '\u{1F1F1}\u{1F1FE}' },
  { code: 'LI', name: 'Liechtenstein', nameEn: 'Liechtenstein', flag: '\u{1F1F1}\u{1F1EE}' },
  { code: 'LT', name: 'Lituanie', nameEn: 'Lithuania', flag: '\u{1F1F1}\u{1F1F9}' },
  { code: 'LU', name: 'Luxembourg', nameEn: 'Luxembourg', flag: '\u{1F1F1}\u{1F1FA}' },
  { code: 'MK', name: 'Mac\u00e9doine du Nord', nameEn: 'North Macedonia', flag: '\u{1F1F2}\u{1F1F0}' },
  { code: 'MG', name: 'Madagascar', nameEn: 'Madagascar', flag: '\u{1F1F2}\u{1F1EC}' },
  { code: 'MY', name: 'Malaisie', nameEn: 'Malaysia', flag: '\u{1F1F2}\u{1F1FE}' },
  { code: 'MW', name: 'Malawi', nameEn: 'Malawi', flag: '\u{1F1F2}\u{1F1FC}' },
  { code: 'MV', name: 'Maldives', nameEn: 'Maldives', flag: '\u{1F1F2}\u{1F1FB}' },
  { code: 'ML', name: 'Mali', nameEn: 'Mali', flag: '\u{1F1F2}\u{1F1F1}' },
  { code: 'MT', name: 'Malte', nameEn: 'Malta', flag: '\u{1F1F2}\u{1F1F9}' },
  { code: 'MA', name: 'Maroc', nameEn: 'Morocco', flag: '\u{1F1F2}\u{1F1E6}' },
  { code: 'MU', name: 'Maurice', nameEn: 'Mauritius', flag: '\u{1F1F2}\u{1F1FA}' },
  { code: 'MR', name: 'Mauritanie', nameEn: 'Mauritania', flag: '\u{1F1F2}\u{1F1F7}' },
  { code: 'MX', name: 'Mexique', nameEn: 'Mexico', flag: '\u{1F1F2}\u{1F1FD}' },
  { code: 'FM', name: 'Micron\u00e9sie', nameEn: 'Micronesia', flag: '\u{1F1EB}\u{1F1F2}' },
  { code: 'MD', name: 'Moldavie', nameEn: 'Moldova', flag: '\u{1F1F2}\u{1F1E9}' },
  { code: 'MC', name: 'Monaco', nameEn: 'Monaco', flag: '\u{1F1F2}\u{1F1E8}' },
  { code: 'MN', name: 'Mongolie', nameEn: 'Mongolia', flag: '\u{1F1F2}\u{1F1F3}' },
  { code: 'ME', name: 'Mont\u00e9n\u00e9gro', nameEn: 'Montenegro', flag: '\u{1F1F2}\u{1F1EA}' },
  { code: 'MZ', name: 'Mozambique', nameEn: 'Mozambique', flag: '\u{1F1F2}\u{1F1FF}' },
  { code: 'MM', name: 'Myanmar', nameEn: 'Myanmar', flag: '\u{1F1F2}\u{1F1F2}' },
  { code: 'NA', name: 'Namibie', nameEn: 'Namibia', flag: '\u{1F1F3}\u{1F1E6}' },
  { code: 'NR', name: 'Nauru', nameEn: 'Nauru', flag: '\u{1F1F3}\u{1F1F7}' },
  { code: 'NP', name: 'N\u00e9pal', nameEn: 'Nepal', flag: '\u{1F1F3}\u{1F1F5}' },
  { code: 'NI', name: 'Nicaragua', nameEn: 'Nicaragua', flag: '\u{1F1F3}\u{1F1EE}' },
  { code: 'NE', name: 'Niger', nameEn: 'Niger', flag: '\u{1F1F3}\u{1F1EA}' },
  { code: 'NG', name: 'Nig\u00e9ria', nameEn: 'Nigeria', flag: '\u{1F1F3}\u{1F1EC}' },
  { code: 'NO', name: 'Norv\u00e8ge', nameEn: 'Norway', flag: '\u{1F1F3}\u{1F1F4}' },
  { code: 'NZ', name: 'Nouvelle-Z\u00e9lande', nameEn: 'New Zealand', flag: '\u{1F1F3}\u{1F1FF}' },
  { code: 'OM', name: 'Oman', nameEn: 'Oman', flag: '\u{1F1F4}\u{1F1F2}' },
  { code: 'UG', name: 'Ouganda', nameEn: 'Uganda', flag: '\u{1F1FA}\u{1F1EC}' },
  { code: 'UZ', name: 'Ouzb\u00e9kistan', nameEn: 'Uzbekistan', flag: '\u{1F1FA}\u{1F1FF}' },
  { code: 'PK', name: 'Pakistan', nameEn: 'Pakistan', flag: '\u{1F1F5}\u{1F1F0}' },
  { code: 'PW', name: 'Palaos', nameEn: 'Palau', flag: '\u{1F1F5}\u{1F1FC}' },
  { code: 'PS', name: 'Palestine', nameEn: 'Palestine', flag: '\u{1F1F5}\u{1F1F8}' },
  { code: 'PA', name: 'Panama', nameEn: 'Panama', flag: '\u{1F1F5}\u{1F1E6}' },
  { code: 'PG', name: 'Papouasie-Nouvelle-Guin\u00e9e', nameEn: 'Papua New Guinea', flag: '\u{1F1F5}\u{1F1EC}' },
  { code: 'PY', name: 'Paraguay', nameEn: 'Paraguay', flag: '\u{1F1F5}\u{1F1FE}' },
  { code: 'NL', name: 'Pays-Bas', nameEn: 'Netherlands', flag: '\u{1F1F3}\u{1F1F1}' },
  { code: 'PE', name: 'P\u00e9rou', nameEn: 'Peru', flag: '\u{1F1F5}\u{1F1EA}' },
  { code: 'PH', name: 'Philippines', nameEn: 'Philippines', flag: '\u{1F1F5}\u{1F1ED}' },
  { code: 'PL', name: 'Pologne', nameEn: 'Poland', flag: '\u{1F1F5}\u{1F1F1}' },
  { code: 'PT', name: 'Portugal', nameEn: 'Portugal', flag: '\u{1F1F5}\u{1F1F9}' },
  { code: 'QA', name: 'Qatar', nameEn: 'Qatar', flag: '\u{1F1F6}\u{1F1E6}' },
  { code: 'DO', name: 'R\u00e9publique dominicaine', nameEn: 'Dominican Republic', flag: '\u{1F1E9}\u{1F1F4}' },
  { code: 'CZ', name: 'R\u00e9publique tch\u00e8que', nameEn: 'Czech Republic', flag: '\u{1F1E8}\u{1F1FF}' },
  { code: 'RO', name: 'Roumanie', nameEn: 'Romania', flag: '\u{1F1F7}\u{1F1F4}' },
  { code: 'GB', name: 'Royaume-Uni', nameEn: 'United Kingdom', flag: '\u{1F1EC}\u{1F1E7}' },
  { code: 'RU', name: 'Russie', nameEn: 'Russia', flag: '\u{1F1F7}\u{1F1FA}' },
  { code: 'RW', name: 'Rwanda', nameEn: 'Rwanda', flag: '\u{1F1F7}\u{1F1FC}' },
  { code: 'KN', name: 'Saint-Kitts-et-Nevis', nameEn: 'Saint Kitts and Nevis', flag: '\u{1F1F0}\u{1F1F3}' },
  { code: 'VC', name: 'Saint-Vincent-et-les-Grenadines', nameEn: 'Saint Vincent and the Grenadines', flag: '\u{1F1FB}\u{1F1E8}' },
  { code: 'LC', name: 'Sainte-Lucie', nameEn: 'Saint Lucia', flag: '\u{1F1F1}\u{1F1E8}' },
  { code: 'SB', name: '\u00celes Salomon', nameEn: 'Solomon Islands', flag: '\u{1F1F8}\u{1F1E7}' },
  { code: 'SV', name: 'Salvador', nameEn: 'El Salvador', flag: '\u{1F1F8}\u{1F1FB}' },
  { code: 'WS', name: 'Samoa', nameEn: 'Samoa', flag: '\u{1F1FC}\u{1F1F8}' },
  { code: 'SM', name: 'Saint-Marin', nameEn: 'San Marino', flag: '\u{1F1F8}\u{1F1F2}' },
  { code: 'ST', name: 'Sao Tom\u00e9-et-Pr\u00edncipe', nameEn: 'Sao Tome and Principe', flag: '\u{1F1F8}\u{1F1F9}' },
  { code: 'SN', name: 'S\u00e9n\u00e9gal', nameEn: 'Senegal', flag: '\u{1F1F8}\u{1F1F3}' },
  { code: 'RS', name: 'Serbie', nameEn: 'Serbia', flag: '\u{1F1F7}\u{1F1F8}' },
  { code: 'SC', name: 'Seychelles', nameEn: 'Seychelles', flag: '\u{1F1F8}\u{1F1E8}' },
  { code: 'SL', name: 'Sierra Leone', nameEn: 'Sierra Leone', flag: '\u{1F1F8}\u{1F1F1}' },
  { code: 'SG', name: 'Singapour', nameEn: 'Singapore', flag: '\u{1F1F8}\u{1F1EC}' },
  { code: 'SK', name: 'Slovaquie', nameEn: 'Slovakia', flag: '\u{1F1F8}\u{1F1F0}' },
  { code: 'SI', name: 'Slov\u00e9nie', nameEn: 'Slovenia', flag: '\u{1F1F8}\u{1F1EE}' },
  { code: 'SO', name: 'Somalie', nameEn: 'Somalia', flag: '\u{1F1F8}\u{1F1F4}' },
  { code: 'SD', name: 'Soudan', nameEn: 'Sudan', flag: '\u{1F1F8}\u{1F1E9}' },
  { code: 'SS', name: 'Soudan du Sud', nameEn: 'South Sudan', flag: '\u{1F1F8}\u{1F1F8}' },
  { code: 'LK', name: 'Sri Lanka', nameEn: 'Sri Lanka', flag: '\u{1F1F1}\u{1F1F0}' },
  { code: 'SE', name: 'Su\u00e8de', nameEn: 'Sweden', flag: '\u{1F1F8}\u{1F1EA}' },
  { code: 'CH', name: 'Suisse', nameEn: 'Switzerland', flag: '\u{1F1E8}\u{1F1ED}' },
  { code: 'SR', name: 'Suriname', nameEn: 'Suriname', flag: '\u{1F1F8}\u{1F1F7}' },
  { code: 'SY', name: 'Syrie', nameEn: 'Syria', flag: '\u{1F1F8}\u{1F1FE}' },
  { code: 'TJ', name: 'Tadjikistan', nameEn: 'Tajikistan', flag: '\u{1F1F9}\u{1F1EF}' },
  { code: 'TZ', name: 'Tanzanie', nameEn: 'Tanzania', flag: '\u{1F1F9}\u{1F1FF}' },
  { code: 'TD', name: 'Tchad', nameEn: 'Chad', flag: '\u{1F1F9}\u{1F1E9}' },
  { code: 'TH', name: 'Tha\u00eflande', nameEn: 'Thailand', flag: '\u{1F1F9}\u{1F1ED}' },
  { code: 'TL', name: 'Timor oriental', nameEn: 'East Timor', flag: '\u{1F1F9}\u{1F1F1}' },
  { code: 'TG', name: 'Togo', nameEn: 'Togo', flag: '\u{1F1F9}\u{1F1EC}' },
  { code: 'TO', name: 'Tonga', nameEn: 'Tonga', flag: '\u{1F1F9}\u{1F1F4}' },
  { code: 'TT', name: 'Trinit\u00e9-et-Tobago', nameEn: 'Trinidad and Tobago', flag: '\u{1F1F9}\u{1F1F9}' },
  { code: 'TN', name: 'Tunisie', nameEn: 'Tunisia', flag: '\u{1F1F9}\u{1F1F3}' },
  { code: 'TM', name: 'Turkm\u00e9nistan', nameEn: 'Turkmenistan', flag: '\u{1F1F9}\u{1F1F2}' },
  { code: 'TR', name: 'Turquie', nameEn: 'Turkey', flag: '\u{1F1F9}\u{1F1F7}' },
  { code: 'TV', name: 'Tuvalu', nameEn: 'Tuvalu', flag: '\u{1F1F9}\u{1F1FB}' },
  { code: 'UA', name: 'Ukraine', nameEn: 'Ukraine', flag: '\u{1F1FA}\u{1F1E6}' },
  { code: 'UY', name: 'Uruguay', nameEn: 'Uruguay', flag: '\u{1F1FA}\u{1F1FE}' },
  { code: 'VU', name: 'Vanuatu', nameEn: 'Vanuatu', flag: '\u{1F1FB}\u{1F1FA}' },
  { code: 'VA', name: 'Vatican', nameEn: 'Vatican City', flag: '\u{1F1FB}\u{1F1E6}' },
  { code: 'VE', name: 'Venezuela', nameEn: 'Venezuela', flag: '\u{1F1FB}\u{1F1EA}' },
  { code: 'VN', name: 'Vi\u00eat Nam', nameEn: 'Vietnam', flag: '\u{1F1FB}\u{1F1F3}' },
  { code: 'YE', name: 'Y\u00e9men', nameEn: 'Yemen', flag: '\u{1F1FE}\u{1F1EA}' },
  { code: 'ZM', name: 'Zambie', nameEn: 'Zambia', flag: '\u{1F1FF}\u{1F1F2}' },
  { code: 'ZW', name: 'Zimbabwe', nameEn: 'Zimbabwe', flag: '\u{1F1FF}\u{1F1FC}' },
  { code: 'AI', name: 'Anguilla', nameEn: 'Anguilla', flag: '\u{1F1E6}\u{1F1EE}' },
  { code: 'BM', name: 'Bermudes', nameEn: 'Bermuda', flag: '\u{1F1E7}\u{1F1F2}' },
  { code: 'VG', name: '\u00celes Vierges britanniques', nameEn: 'British Virgin Islands', flag: '\u{1F1FB}\u{1F1EC}' },
  { code: 'KY', name: '\u00celes Ca\u00efmans', nameEn: 'Cayman Islands', flag: '\u{1F1F0}\u{1F1FE}' },
  { code: 'CK', name: '\u00celes Cook', nameEn: 'Cook Islands', flag: '\u{1F1E8}\u{1F1F0}' },
  { code: 'CW', name: 'Cura\u00e7ao', nameEn: 'Curacao', flag: '\u{1F1E8}\u{1F1FC}' },
  { code: 'FK', name: '\u00celes Malouines', nameEn: 'Falkland Islands', flag: '\u{1F1EB}\u{1F1F0}' },
  { code: 'FO', name: '\u00celes F\u00e9ro\u00e9', nameEn: 'Faroe Islands', flag: '\u{1F1EB}\u{1F1F4}' },
  { code: 'GF', name: 'Guyane fran\u00e7aise', nameEn: 'French Guiana', flag: '\u{1F1EC}\u{1F1EB}' },
  { code: 'PF', name: 'Polyn\u00e9sie fran\u00e7aise', nameEn: 'French Polynesia', flag: '\u{1F1F5}\u{1F1EB}' },
  { code: 'GI', name: 'Gibraltar', nameEn: 'Gibraltar', flag: '\u{1F1EC}\u{1F1EE}' },
  { code: 'GL', name: 'Groenland', nameEn: 'Greenland', flag: '\u{1F1EC}\u{1F1F1}' },
  { code: 'GP', name: 'Guadeloupe', nameEn: 'Guadeloupe', flag: '\u{1F1EC}\u{1F1F5}' },
  { code: 'GU', name: 'Guam', nameEn: 'Guam', flag: '\u{1F1EC}\u{1F1FA}' },
  { code: 'HK', name: 'Hong Kong', nameEn: 'Hong Kong', flag: '\u{1F1ED}\u{1F1F0}' },
  { code: 'IM', name: '\u00cele de Man', nameEn: 'Isle of Man', flag: '\u{1F1EE}\u{1F1F2}' },
  { code: 'JE', name: 'Jersey', nameEn: 'Jersey', flag: '\u{1F1EF}\u{1F1EA}' },
  { code: 'GG', name: 'Guernesey', nameEn: 'Guernsey', flag: '\u{1F1EC}\u{1F1EC}' },
  { code: 'XK', name: 'Kosovo', nameEn: 'Kosovo', flag: '\u{1F1FD}\u{1F1F0}' },
  { code: 'MO', name: 'Macao', nameEn: 'Macau', flag: '\u{1F1F2}\u{1F1F4}' },
  { code: 'MQ', name: 'Martinique', nameEn: 'Martinique', flag: '\u{1F1F2}\u{1F1F6}' },
  { code: 'YT', name: 'Mayotte', nameEn: 'Mayotte', flag: '\u{1F1FE}\u{1F1F9}' },
  { code: 'MS', name: 'Montserrat', nameEn: 'Montserrat', flag: '\u{1F1F2}\u{1F1F8}' },
  { code: 'NC', name: 'Nouvelle-Cal\u00e9donie', nameEn: 'New Caledonia', flag: '\u{1F1F3}\u{1F1E8}' },
  { code: 'NU', name: 'Niou\u00e9', nameEn: 'Niue', flag: '\u{1F1F3}\u{1F1FA}' },
  { code: 'NF', name: '\u00cele Norfolk', nameEn: 'Norfolk Island', flag: '\u{1F1F3}\u{1F1EB}' },
  { code: 'MP', name: '\u00celes Mariannes du Nord', nameEn: 'Northern Mariana Islands', flag: '\u{1F1F2}\u{1F1F5}' },
  { code: 'PR', name: 'Porto Rico', nameEn: 'Puerto Rico', flag: '\u{1F1F5}\u{1F1F7}' },
  { code: 'RE', name: 'La R\u00e9union', nameEn: 'Reunion', flag: '\u{1F1F7}\u{1F1EA}' },
  { code: 'BL', name: 'Saint-Barth\u00e9lemy', nameEn: 'Saint Barthelemy', flag: '\u{1F1E7}\u{1F1F1}' },
  { code: 'SH', name: 'Sainte-H\u00e9l\u00e8ne', nameEn: 'Saint Helena', flag: '\u{1F1F8}\u{1F1ED}' },
  { code: 'MF', name: 'Saint-Martin', nameEn: 'Saint Martin', flag: '\u{1F1F2}\u{1F1EB}' },
  { code: 'PM', name: 'Saint-Pierre-et-Miquelon', nameEn: 'Saint Pierre and Miquelon', flag: '\u{1F1F5}\u{1F1F2}' },
  { code: 'SX', name: 'Sint Maarten', nameEn: 'Sint Maarten', flag: '\u{1F1F8}\u{1F1FD}' },
  { code: 'TC', name: '\u00celes Turques-et-Ca\u00efques', nameEn: 'Turks and Caicos Islands', flag: '\u{1F1F9}\u{1F1E8}' },
  { code: 'VI', name: '\u00celes Vierges am\u00e9ricaines', nameEn: 'US Virgin Islands', flag: '\u{1F1FB}\u{1F1EE}' },
  { code: 'WF', name: 'Wallis-et-Futuna', nameEn: 'Wallis and Futuna', flag: '\u{1F1FC}\u{1F1EB}' },
  { code: 'EH', name: 'Sahara occidental', nameEn: 'Western Sahara', flag: '\u{1F1EA}\u{1F1ED}' },
  { code: 'TW', name: 'Ta\u00efwan', nameEn: 'Taiwan', flag: '\u{1F1F9}\u{1F1FC}' },
  { code: 'AW', name: 'Aruba', nameEn: 'Aruba', flag: '\u{1F1E6}\u{1F1FC}' },
  { code: 'AX', name: '\u00celes \u00c5land', nameEn: 'Aland Islands', flag: '\u{1F1E6}\u{1F1FD}' },
  { code: 'BQ', name: 'Bonaire, Saint-Eustache et Saba', nameEn: 'Caribbean Netherlands', flag: '\u{1F1E7}\u{1F1F6}' },
  { code: 'IO', name: "Territoire britannique de l'oc\u00e9an Indien", nameEn: 'British Indian Ocean Territory', flag: '\u{1F1EE}\u{1F1F4}' },
  { code: 'TF', name: 'Terres australes fran\u00e7aises', nameEn: 'French Southern Territories', flag: '\u{1F1F9}\u{1F1EB}' },
  { code: 'AS', name: 'Samoa am\u00e9ricaines', nameEn: 'American Samoa', flag: '\u{1F1E6}\u{1F1F8}' },
  { code: 'TK', name: 'Tokelau', nameEn: 'Tokelau', flag: '\u{1F1F9}\u{1F1F0}' },
  { code: 'PN', name: 'Pitcairn', nameEn: 'Pitcairn Islands', flag: '\u{1F1F5}\u{1F1F3}' },
  { code: 'GS', name: 'G\u00e9orgie du Sud-et-les \u00celes Sandwich du Sud', nameEn: 'South Georgia and the South Sandwich Islands', flag: '\u{1F1EC}\u{1F1F8}' },
  { code: 'CC', name: '\u00celes Cocos', nameEn: 'Cocos (Keeling) Islands', flag: '\u{1F1E8}\u{1F1E8}' },
  { code: 'CX', name: '\u00cele Christmas', nameEn: 'Christmas Island', flag: '\u{1F1E8}\u{1F1FD}' },
  { code: 'MH', name: '\u00celes Marshall', nameEn: 'Marshall Islands', flag: '\u{1F1F2}\u{1F1ED}' },
];
