-- V10: introduce USER_ROLE_ASSIGNMENTS junction, backfill PRO + ADMIN, drop USERS.ROLE.
--
-- EMPLOYEEs are NOT backfilled here because EMPLOYEES live in tenant schemas;
-- the Java EmployeeRoleBackfillRunner takes care of them at boot (Task 9).

-- 1. Table
CREATE TABLE USER_ROLE_ASSIGNMENTS (
    ID         NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID    NUMBER(19) NOT NULL,
    ROLE       VARCHAR2(32 CHAR) NOT NULL,
    SCOPE_TYPE VARCHAR2(16 CHAR) NOT NULL,
    SCOPE_ID   NUMBER(19),
    CREATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_URA_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    CONSTRAINT UK_USER_ROLE_SCOPE UNIQUE (USER_ID, ROLE, SCOPE_TYPE, SCOPE_ID),
    CONSTRAINT CK_URA_SCOPE_TYPE CHECK (SCOPE_TYPE IN ('GLOBAL', 'TENANT')),
    CONSTRAINT CK_URA_SCOPE_MATCH CHECK (
        (SCOPE_TYPE = 'TENANT' AND SCOPE_ID IS NOT NULL) OR
        (SCOPE_TYPE = 'GLOBAL' AND SCOPE_ID IS NULL)
    )
);

CREATE INDEX IX_URA_USER ON USER_ROLE_ASSIGNMENTS (USER_ID);
CREATE INDEX IX_URA_SCOPE ON USER_ROLE_ASSIGNMENTS (SCOPE_TYPE, SCOPE_ID);

-- 2. Backfill PRO@TENANT: one row per (user, owned tenant)
INSERT INTO USER_ROLE_ASSIGNMENTS (USER_ID, ROLE, SCOPE_TYPE, SCOPE_ID, CREATED_AT)
SELECT u.ID, 'PRO', 'TENANT', t.ID, CURRENT_TIMESTAMP
FROM USERS u
JOIN TENANTS t ON t.OWNER_ID = u.ID
WHERE u.ROLE = 'PRO';

-- 3. Backfill ADMIN@GLOBAL
INSERT INTO USER_ROLE_ASSIGNMENTS (USER_ID, ROLE, SCOPE_TYPE, SCOPE_ID, CREATED_AT)
SELECT ID, 'ADMIN', 'GLOBAL', NULL, CURRENT_TIMESTAMP
FROM USERS WHERE ROLE = 'ADMIN';

-- 4. Drop the CK_USERS_ROLE constraint (created by V2) before dropping the column.
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'USERS' AND CONSTRAINT_NAME = 'CK_USERS_ROLE';
    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE USERS DROP CONSTRAINT CK_USERS_ROLE';
    END IF;
END;
/

-- 5. Drop the USERS.ROLE column
ALTER TABLE USERS SET UNUSED COLUMN ROLE;
ALTER TABLE USERS DROP UNUSED COLUMNS;
