-- V5: backfill nullable defaults on TENANTS rows that pre-date their columns.
--
-- Reproduces ApplicationSchemaMigrator.backfillTenantDefaults(). Each statement
-- is naturally idempotent thanks to "WHERE col IS NULL". Flyway manages the
-- transaction — do not COMMIT here.
UPDATE TENANTS SET CLOSED_ON_HOLIDAYS = 1       WHERE CLOSED_ON_HOLIDAYS IS NULL;
UPDATE TENANTS SET BUFFER_MINUTES = 0           WHERE BUFFER_MINUTES IS NULL;
UPDATE TENANTS SET MIN_ADVANCE_MINUTES = 120    WHERE MIN_ADVANCE_MINUTES IS NULL;
UPDATE TENANTS SET MAX_ADVANCE_DAYS = 90        WHERE MAX_ADVANCE_DAYS IS NULL;
UPDATE TENANTS SET MAX_CLIENT_HOURS_PER_DAY = 8 WHERE MAX_CLIENT_HOURS_PER_DAY IS NULL;
UPDATE TENANTS SET ANNUAL_LEAVE_DAYS = 25       WHERE ANNUAL_LEAVE_DAYS IS NULL;
UPDATE TENANTS SET EMPLOYEES_ENABLED = 0        WHERE EMPLOYEES_ENABLED IS NULL;
