-- Salon storefront preview share tokens (Jalon 5).
--
-- A pro can mint a URL-safe token that grants temporary, revokable access
-- to their DRAFT storefront. The token is checked by PublicSalonController
-- when ?preview=<token> is present and the tenant is DRAFT.
--
-- Tolerance for fresh databases: Flyway runs before Hibernate ddl-auto, so on
-- a brand-new schema TENANTS does not exist yet. In that case we skip
-- silently and let Hibernate create the table during the same boot.
--
-- Tolerance for existing or partially provisioned databases:
--   * table already exists -> swallow ORA-00955
--   * FK already exists (same or different name) -> swallow ORA-02264/-02275
--   * index already exists -> swallow ORA-00955/-01408

DECLARE
    e_object_exists         EXCEPTION;
    e_index_exists          EXCEPTION;
    e_constraint_name_used  EXCEPTION;
    e_fk_already_exists     EXCEPTION;
    v_tenants_exists        NUMBER;
    PRAGMA EXCEPTION_INIT(e_object_exists, -955);
    PRAGMA EXCEPTION_INIT(e_index_exists, -1408);
    PRAGMA EXCEPTION_INIT(e_constraint_name_used, -2264);
    PRAGMA EXCEPTION_INIT(e_fk_already_exists, -2275);
BEGIN
    SELECT COUNT(*) INTO v_tenants_exists
      FROM user_tables
     WHERE table_name = 'TENANTS';
    IF v_tenants_exists = 0 THEN
        RETURN;
    END IF;

    BEGIN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE SALON_PREVIEW_TOKENS (
                ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                TENANT_ID NUMBER(19) NOT NULL,
                TOKEN VARCHAR2(64 CHAR) NOT NULL,
                CREATED_AT TIMESTAMP NOT NULL,
                EXPIRES_AT TIMESTAMP NULL,
                REVOKED_AT TIMESTAMP NULL,
                CONSTRAINT UK_PREVIEW_TOKEN_TOKEN UNIQUE (TOKEN)
            )
        ]';
    EXCEPTION
        WHEN e_object_exists THEN NULL;
    END;

    BEGIN
        EXECUTE IMMEDIATE
            'ALTER TABLE SALON_PREVIEW_TOKENS ADD CONSTRAINT FK_PREVIEW_TOKEN_TENANT ' ||
            'FOREIGN KEY (TENANT_ID) REFERENCES TENANTS(ID) ON DELETE CASCADE';
    EXCEPTION
        WHEN e_constraint_name_used THEN NULL;
        WHEN e_fk_already_exists THEN NULL;
    END;

    BEGIN
        EXECUTE IMMEDIATE
            'CREATE INDEX IX_PREVIEW_TOKEN_TENANT ON SALON_PREVIEW_TOKENS (TENANT_ID)';
    EXCEPTION
        WHEN e_object_exists THEN NULL;
        WHEN e_index_exists THEN NULL;
    END;
END;
/
