-- Salon storefront preview share tokens (Jalon 5).
--
-- A pro can mint a URL-safe token that grants temporary, revokable access
-- to their DRAFT storefront. The token is checked by PublicSalonController
-- when ?preview=<token> is present and the tenant is DRAFT.

CREATE TABLE SALON_PREVIEW_TOKENS (
    id          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   NUMBER(19) NOT NULL,
    token       VARCHAR2(64) NOT NULL,
    created_at  TIMESTAMP NOT NULL,
    expires_at  TIMESTAMP NULL,
    revoked_at  TIMESTAMP NULL,
    CONSTRAINT FK_PREVIEW_TOKEN_TENANT
        FOREIGN KEY (tenant_id) REFERENCES TENANTS(id) ON DELETE CASCADE,
    CONSTRAINT UK_PREVIEW_TOKEN_TOKEN UNIQUE (token)
);

CREATE INDEX IX_PREVIEW_TOKEN_TENANT ON SALON_PREVIEW_TOKENS (tenant_id);
