-- ── MAIL_OUTBOX : transactional outbox for mail delivery ──
-- Rows are INSERTed by MailOutboxService.queue() inside the caller's transaction
-- (rollback-safe). A scheduled worker dequeues PENDING rows with FOR UPDATE
-- SKIP LOCKED and sends via the configured MailSender (smtp / postmark).
CREATE TABLE MAIL_OUTBOX (
    ID                    NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TEMPLATE              VARCHAR2(64 CHAR) NOT NULL,
    RECIPIENT_EMAIL       VARCHAR2(320 CHAR) NOT NULL,
    TENANT_SLUG           VARCHAR2(64 CHAR),
    VARS_JSON             CLOB NOT NULL,
    STATUS                VARCHAR2(32 CHAR) DEFAULT 'PENDING' NOT NULL,
    ATTEMPTS              NUMBER(5) DEFAULT 0 NOT NULL,
    NEXT_ATTEMPT_AT       TIMESTAMP NOT NULL,
    LAST_ERROR            VARCHAR2(2000 CHAR),
    PROVIDER_MESSAGE_ID   VARCHAR2(255 CHAR),
    CREATED_AT            TIMESTAMP NOT NULL,
    SENT_AT               TIMESTAMP,
    DELIVERED_AT          TIMESTAMP,
    CONSTRAINT CK_MAIL_OUTBOX_STATUS CHECK (STATUS IN ('PENDING','IN_FLIGHT','SENT','PERMANENTLY_FAILED'))
);

CREATE INDEX IX_MAIL_OUTBOX_PENDING ON MAIL_OUTBOX (STATUS, NEXT_ATTEMPT_AT);
CREATE INDEX IX_MAIL_OUTBOX_PROVIDER_MSG ON MAIL_OUTBOX (PROVIDER_MESSAGE_ID);
