package com.prettyface.app.auth;

import com.prettyface.app.users.domain.AuthProvider;
import com.prettyface.app.users.domain.Role;
import com.prettyface.app.users.domain.User;
import com.prettyface.app.users.repo.UserRepository;
import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.mock.web.MockHttpServletRequest;
import org.springframework.mock.web.MockHttpServletResponse;
import org.springframework.security.core.Authentication;
import org.springframework.test.util.ReflectionTestUtils;

import javax.crypto.SecretKey;
import java.nio.charset.StandardCharsets;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class OAuth2AuthenticationSuccessHandlerTests {

    @Mock
    private UserRepository userRepository;

    private TokenService tokenService;
    private OAuth2AuthenticationSuccessHandler handler;

    private static final String TEST_SECRET = "test-secret-key-for-unit-tests-min-32-bytes-ok";
    private static final String REDIRECT_URI = "http://localhost:4300/oauth2/redirect";

    @BeforeEach
    void setUp() {
        tokenService = new TokenService();
        ReflectionTestUtils.setField(tokenService, "tokenSecret", TEST_SECRET);
        ReflectionTestUtils.setField(tokenService, "tokenExpirationMs", 86400000L);

        handler = new OAuth2AuthenticationSuccessHandler(tokenService, userRepository);
        ReflectionTestUtils.setField(handler, "authorizedRedirectUri", REDIRECT_URI);
    }

    // B2.4: Token generated by success handler contains email and role claims
    @Test
    void onAuthenticationSuccess_generatesTokenWithEmailAndRole() throws Exception {
        User user = User.builder()
            .id(1L)
            .name("Sophie Martin")
            .email("sophie@salon.fr")
            .provider(AuthProvider.GOOGLE)
            .role(Role.PRO)
            .emailVerified(true)
            .build();

        when(userRepository.findById(1L)).thenReturn(Optional.of(user));

        CustomOAuth2User oAuth2User = mock(CustomOAuth2User.class);
        when(oAuth2User.getUserId()).thenReturn(1L);

        Authentication authentication = mock(Authentication.class);
        when(authentication.getPrincipal()).thenReturn(oAuth2User);

        MockHttpServletRequest request = new MockHttpServletRequest();
        MockHttpServletResponse response = new MockHttpServletResponse();

        handler.onAuthenticationSuccess(request, response, authentication);

        // Parse redirect URL and extract token
        String location = response.getRedirectedUrl();
        assertThat(location).isNotNull().startsWith(REDIRECT_URI + "?token=");

        String token = location.substring(location.indexOf("token=") + 6);

        // Decode and verify JWT claims
        SecretKey key = Keys.hmacShaKeyFor(TEST_SECRET.getBytes(StandardCharsets.UTF_8));
        Claims claims = Jwts.parser()
            .verifyWith(key)
            .build()
            .parseSignedClaims(token)
            .getPayload();

        assertThat(claims.getSubject()).isEqualTo("1");
        assertThat(claims.get("email", String.class)).isEqualTo("sophie@salon.fr");
        assertThat(claims.get("role", String.class)).isEqualTo("PRO");
    }
}
