package com.fleurdecoquillage.app.common.security;

import org.springframework.security.web.csrf.CsrfToken;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Controller to expose CSRF token for SPA (Angular).
 * The token is automatically generated by Spring Security and exposed via cookie (XSRF-TOKEN).
 * This endpoint allows the frontend to trigger token generation on app startup.
 */
@RestController
@RequestMapping("/api/csrf")
public class CsrfController {

    /**
     * Endpoint to get CSRF token.
     * Spring Security automatically generates the token and sets it in a cookie named XSRF-TOKEN.
     * The frontend can read this cookie and send it back in the X-XSRF-TOKEN header.
     *
     * @param token Injected by Spring Security
     * @return CSRF token details (for debugging)
     */
    @GetMapping
    public CsrfTokenResponse getCsrfToken(CsrfToken token) {
        return new CsrfTokenResponse(
                token.getToken(),
                token.getHeaderName(),
                token.getParameterName()
        );
    }

    /**
     * DTO for CSRF token response
     */
    public record CsrfTokenResponse(
            String token,
            String headerName,
            String parameterName
    ) {}
}
